
version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=realcompany
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$root --password=$$root
      timeout: 10s
      retries: 10


  nextjs-app:
    container_name: govt-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
volumes:
  db:
    driver: local